name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 mypy black isort

    - name: Check code formatting (black)
      run: black --check .

    - name: Check imports ordering (isort)
      run: isort --check-only --diff .

    - name: Lint with flake8
      run: flake8 . --count --max-line-length=88 --statistics

    - name: Type checking with mypy
      run: mypy core tests --strict

    - name: Run tests with pytest
      run: |
        pytest --cov=core --cov-report=xml

    - name: Check directory structure
      run: |
        for dir in core tests "recetas/sin_procesar" "recetas/procesadas/Receta Original" "recetas/procesadas/Recetas JSON" "recetas/procesadas/Recetas MD"; do
          if [ ! -d "$dir" ]; then
            echo "Required directory $dir is missing"
            exit 1
          fi
        done

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
